### ISSUE TITLE
How to use the project ?

### ISSUE THREAD

**Issue by what951006** [mullvad/libwfp#26]
I am fresh to WFP tech, your code looks fantastic, hope the document writing more detail on how to use this project(more example), may this project needs a driver to work? I was so confused, even I successfully build the project, but I don't  know how to run it~

**Comment by MurylloEx** [comment]
Yes, the code look fantastic but need some docs and samples. I think with a bit of work i can contribute if some help may be useful. 

BTW: Great framework for Firewalls devs.

**Comment by mvd-ows** [comment]
Sorry, had not seen this issue before.

To anyone reading this:

The best advice I can give is read up on WFP and step through the example code. Concepts in the code map very closely to concepts in WFP. If something doesn't make sense it's probably because you need a better understanding of WFP.

This repository will not and cannot address shortcomings in official WFP documentation and examples.

Also, this is a library for building firewalls. It's not a firewall application.

HTH
