### ISSUE TITLE
ObjectEnumerator::Events has a memory leak issue

### ISSUE THREAD

**Issue by windpiaoxue** [mullvad/libwfp#36]
Hello, thank you for opening up a great project.

When I tried to use "ObjectEnumerator::Events", I found that there are a serious memory leak issue. The following is the code.

```cpp
auto engine = wfp::FilterEngine::DynamicSession();
for (;;) {
    wfp::ObjectEnumerator::Events(*engine, [](const FWPM_NET_EVENT0& event) -> bool { return true; });
}
```

**Comment by mvd-ows** [comment]
Thanks for reporting this issue. We've been able to confirm that there is indeed a memory leak running this code on both Windows 10 and Windows 11.

Unfortunately, there doesn't seem to be an easy way to correct the leak, or even to work around it.

By simplifying the code we were able to narrow it down to the API functions `FwpmNetEventEnum0()` and `FwpmFreeMemory0`. It was also confirmed that more recent versions of the enumeration function are also affected, e.g. `FwpmNetEventEnum5()`.

`FwpmFreeMemory0()` is a thin wrapper around `RtlFreeHeap()` so my initial suspicion was that the event items were not entirely self-contained, especially since `FWPM_NET_EVENT0` uses a pointer for the event payload. Verifying the block of memory, there's an array of `FWPM_NET_EVENT0` pointers, followed by the actual `FWPM_NET_EVENT0` instances, and with the payload data neatly embedded in between event instances. So that all seems to be in order.

I then proceeded to sample the calls to `RtlAllocateHeap()` and `RtlFreeHeap()` while `FwpmNetEventEnum0()` was executing. One would expect `n` and `n - 1` calls, respectively, to the allocation functions. The main thread was executing at above average priority but there's still some interference from other activity within the process. Nevertheless, the results seem to indicate quite clearly what the issue is:

```
items		alloc		free
requested

3			38			27
3			40			29
3			40			29
2			32			22
2			30			22
2			30			22
1			22			17
1			22			17
1			24			17
```

At this point there's not much more we can do. All testing and probing performed today indicates that the issue is within the Windows API.

As for work-arounds, you may be able to force the allocations into a different heap which you control. That heap could then be destroyed and recreated at some appropriate time. But this may not be simple/portable/appropriate. Another obvious solution is to perform event extraction in a child process that you spawn specifically for that purpose. Events can then be marshalled back to the main process via some IPC mechanism.

**Comment by windpiaoxue** [comment]
Thank for your reply. I plan to use `FwpmNetEventSubscribe` instead.
